<a href="https://colab.research.google.com/github/sravanireddyseema/Ai-Resume-Builder/blob/main/Data_Immersion_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

In [ ]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [ ]:
df.shape

(1000, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [ ]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [ ]:
df["City"] = df["City"].str.strip().str.title()

In [ ]:
data_cleaning.py

NameError: name 'data_cleaning' is not defined

In [ ]:
df = df.drop_duplicates()

In [ ]:
print("Duplicates after cleaning:", df.duplicated().sum())

Duplicates after cleaning: 0

In [ ]:
print(df.isnull().sum())

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [ ]:
print(df.dtypes)

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [ ]:
print(df.isnull().sum())

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [ ]:
print(df.dtypes)

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [ ]:
print("Duplicates:", df.duplicated().sum())

Duplicates: 0

In [ ]:
import pandas as pd

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

print(df.head())
print(df.info())

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# Check duplicates
print("\nDuplicates:")
print(df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

# Standardize City
df["City"] = df["City"].str.strip().str.title()

# Check again after cleaning
print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

print("\nDuplicates after cleaning:")
print(df.duplicated().sum())

    Order_ID  Order_Date Customer_ID Customer_Name   Age  Gender       City  \
0  ORD100002  2025-02-25    CUST5529  Customer_227  30.0  Female  Bengaluru
1  ORD100003  2025-10-14    CUST3127  Customer_182  63.0    Male  Bengaluru
2  ORD100004  2025-05-13    CUST8887  Customer_487  62.0  Female  Bengaluru
3  ORD100005  2025-12-02    CUST2515  Customer_470  65.0  Female    Kolkata
4  ORD100006  2025-11-20    CUST4796  Customer_380  44.0    Male  Bengaluru

  Product     Category  Quantity  Unit_Price  Total_Sales
0    Rice      Grocery         7     2829.77     19808.39
1    Book    Education         5    27906.16    139530.80
2    Book    Education         8    37491.06    299928.48
3  Mobile  Electronics         9    28541.36    256872.24
4    Rice      Grocery        10    14036.59    140365.90
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB
None

Missing values:
Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

Duplicates:
0

Missing values after cleaning:
Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

Data types:
Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

Duplicates after cleaning:
0

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [ ]:
print("Missing Age:", df["Age"].isnull().sum())

Missing Age: 0

In [ ]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [ ]:
print(df["Order_Date"].dtype)

datetime64[ns]

In [ ]:
print(df["Age"].describe())

count    1000.000000
mean       41.353000
std        13.683626
min        18.000000
25%        30.000000
50%        41.000000
75%        53.000000
max        65.000000
Name: Age, dtype: float64

In [ ]:
print(df["Quantity"].describe())

count    1000.000000
mean        5.435000
std         2.838632
min         1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Quantity, dtype: float64

In [ ]:
df["Calculated_Sales"] = df["Quantity"] * df["Unit_Price"]

print(
    (df["Total_Sales"] - df["Calculated_Sales"]).abs().max()
)

5.820766091346741e-11

In [ ]:
# Handle missing Age values
df["Age"] = df["Age"].fillna(df["Age"].median())

# Handle missing City values
df["City"] = df["City"].fillna(df["City"].mode()[0])

# Convert Order_Date to datetime
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

# Check Age
print("\nAge statistics:")
print(df["Age"].describe())

# Check Quantity
print("\nQuantity statistics:")
print(df["Quantity"].describe())

# Verify sales calculation
df["Calculated_Sales"] = df["Quantity"] * df["Unit_Price"]

print("\nMaximum sales calculation difference:")
print((df["Total_Sales"] - df["Calculated_Sales"]).abs().max())

Age statistics:
count    1000.000000
mean       41.353000
std        13.683626
min        18.000000
25%        30.000000
50%        41.000000
75%        53.000000
max        65.000000
Name: Age, dtype: float64

Quantity statistics:
count    1000.000000
mean        5.435000
std         2.838632
min         1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Quantity, dtype: float64

Maximum sales calculation difference:
5.820766091346741e-11

In [ ]:
df["Calculated_Sales"] = df["Quantity"] * df["Unit_Price"]

In [ ]:
df = df.drop(columns=["Calculated_Sales"])

In [ ]:
print("\nFINAL DATA QUALITY CHECK")

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nDataset shape:")
print(df.shape)

FINAL DATA QUALITY CHECK

Missing values:
Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

Duplicate rows:
0

Data types:
Order_ID                 object
Order_Date       datetime64[ns]
Customer_ID              object
Customer_Name            object
Age                     float64
Gender                   object
City                     object
Product                  object
Category                 object
Quantity                  int64
Unit_Price              float64
Total_Sales             float64
dtype: object

Dataset shape:
(1000, 12)

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

print("\nCleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
df["Order_Year"] = df["Order_Date"].dt.year

In [ ]:
df["Order_Month"] = df["Order_Date"].dt.month

In [ ]:
df["Order_Month_Name"] = df["Order_Date"].dt.month_name()

In [ ]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[17, 25, 35, 45, 55, 65],
    labels=["18-25", "26-35", "36-45", "46-55", "56-65"]
)

In [ ]:
df["Sales_Category"] = pd.cut(
    df["Total_Sales"],
    bins=[0, 50000, 150000, float("inf")],
    labels=["Low", "Medium", "High"]
)

In [ ]:
print(df.head())
print(df[[
    "Order_Date",
    "Order_Year",
    "Order_Month",
    "Order_Month_Name",
    "Age",
    "Age_Group",
    "Total_Sales",
    "Sales_Category"
]].head(10))

    Order_ID Order_Date Customer_ID Customer_Name   Age  Gender       City  \
0  ORD100002 2025-02-25    CUST5529  Customer_227  30.0  Female  Bengaluru
1  ORD100003 2025-10-14    CUST3127  Customer_182  63.0    Male  Bengaluru
2  ORD100004 2025-05-13    CUST8887  Customer_487  62.0  Female  Bengaluru
3  ORD100005 2025-12-02    CUST2515  Customer_470  65.0  Female    Kolkata
4  ORD100006 2025-11-20    CUST4796  Customer_380  44.0    Male  Bengaluru

  Product     Category  Quantity  Unit_Price  Total_Sales  Order_Year  \
0    Rice      Grocery         7     2829.77     19808.39        2025
1    Book    Education         5    27906.16    139530.80        2025
2    Book    Education         8    37491.06    299928.48        2025
3  Mobile  Electronics         9    28541.36    256872.24        2025
4    Rice      Grocery        10    14036.59    140365.90        2025

   Order_Month Order_Month_Name Age_Group Sales_Category
0            2         February     26-35            Low
1           10          October     56-65         Medium
2            5              May     56-65           High
3           12         December     56-65           High
4           11         November     36-45         Medium
  Order_Date  Order_Year  Order_Month Order_Month_Name   Age Age_Group  \
0 2025-02-25        2025            2         February  30.0     26-35
1 2025-10-14        2025           10          October  63.0     56-65
2 2025-05-13        2025            5              May  62.0     56-65
3 2025-12-02        2025           12         December  65.0     56-65
4 2025-11-20        2025           11         November  44.0     36-45
5 2025-12-31        2025           12         December  40.0     36-45
6 2025-10-14        2025           10          October  61.0     56-65
7 2025-12-05        2025           12         December  35.0     26-35
8 2025-11-21        2025           11         November  41.0     36-45
9 2025-04-16        2025            4            April  30.0     26-35

   Total_Sales Sales_Category
0     19808.39            Low
1    139530.80         Medium
2    299928.48           High
3    256872.24           High
4    140365.90         Medium
5    323527.23           High
6    299985.18           High
7     28466.49            Low
8    116929.38         Medium
9    144194.72         Medium

In [ ]:
print("\nOrder Year:")
print(df["Order_Year"].value_counts())

print("\nOrder Month:")
print(df["Order_Month"].value_counts().sort_index())

print("\nAge Groups:")
print(df["Age_Group"].value_counts().sort_index())

print("\nSales Categories:")
print(df["Sales_Category"].value_counts())

Order Year:
Order_Year
2025    995
2026      5
Name: count, dtype: int64

Order Month:
Order_Month
1     81
2     86
3     89
4     80
5     85
6     83
7     83
8     75
9     79
10    84
11    77
12    98
Name: count, dtype: int64

Age Groups:
Age_Group
18-25    158
26-35    219
36-45    223
46-55    202
56-65    198
Name: count, dtype: int64

Sales Categories:
Sales_Category
High      368
Medium    359
Low       273
Name: count, dtype: int64

In [ ]:
print("\nFINAL DATASET CHECK")

print("Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicates:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

FINAL DATASET CHECK
Shape: (1000, 17)

Missing Values:
Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Age                 0
Gender              0
City                0
Product             0
Category            0
Quantity            0
Unit_Price          0
Total_Sales         0
Order_Year          0
Order_Month         0
Order_Month_Name    0
Age_Group           0
Sales_Category      0
dtype: int64

Duplicates: 0

Data Types:
Order_ID                    object
Order_Date          datetime64[ns]
Customer_ID                 object
Customer_Name               object
Age                        float64
Gender                      object
City                        object
Product                     object
Category                    object
Quantity                     int64
Unit_Price                 float64
Total_Sales                float64
Order_Year                   int32
Order_Month                  int32
Order_Month_Name            object
Age_Group                 category
Sales_Category            category
dtype: object

In [ ]:
df.to_csv("final_cleaned_dataset.csv", index=False)

print("Final cleaned and transformed dataset saved successfully!")

Final cleaned and transformed dataset saved successfully!